name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Type Check
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      # Vercel will automatically deploy when pushing to main
      # This step is for database migrations
      - name: Deploy Database Changes
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: npm run db:deploy
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }} 