name: Deploy Database Changes

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Development' }}

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ github.ref == 'refs/heads/main' && secrets.PRODUCTION_DB_PASSWORD || secrets.DEVELOPMENT_DB_PASSWORD }}
      SUPABASE_PROJECT_REF: ${{ github.ref == 'refs/heads/main' && 'loyxjwbvdluclokdqacn' || 'gnxmyjhxyhyjckymaphq' }}
      SUPABASE_PROJECT_ID: arbor_v0

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy migrations
        run: |
          echo "Deploying to ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }} environment"
          supabase link --project-ref $SUPABASE_PROJECT_REF -p $SUPABASE_DB_PASSWORD
          supabase db push 